### ISSUE TITLE
How to set a color for a light bulb?

### ISSUE THREAD

**Issue by Mezir** [Aymkdn/tuyacloud-php#1]
@Aymkdn How to set a color for a light bulb? Can i give an example.

**Comment by Aymkdn** [comment]
I never tried, but you could try `colorSet`. 
Something like:
```php
$tuya->setState([
  "name" => "my light",
  "command" => "colorSet",
  "value" => {
     "hue":26,
     "saturation":68,
     "brightness":66
  } 
]);
```

I'm not at home until Thursday so I cannot test. Let me know if it works or not.

**Comment by Mezir** [comment]
I did, but no color has set.
```
	$tuya->setState([
	     "id" => "06114800840d8e8c16b1",
	    "command" => "colorSet",
	    "value" => '{"hue":26,"saturation":68,"brightness":66}'
       ]);
```

**Comment by Aymkdn** [comment]
It looks like the payload must be different when we use the colors. So I've just published a new version of the file.

Please, use the new file and try again with the below code (my last example was a mix between JavaScript and PHP... I was doing on my phone and I mixed the two languages ^^):
```php
$tuya->setState([
	     "id" => "06114800840d8e8c16b1",
	    "command" => "colorSet",
	    "value" => [ "hue" => 26, "saturation" => 68, "brightness" => 66 ]
       ]);
```

**Comment by Mezir** [comment]
It works. Where does a color get in? Is there a color list?

**Comment by Aymkdn** [comment]
It's hsv color. You can find here: http://colorizer.org
