### ISSUE TITLE
problem with state

### ISSUE THREAD

**Issue by smashek** [Aymkdn/tuyacloud-php#12]
Hi.
I have a problem with state of a switch. When i set state by Smart Life apk, everything is ok. State is retrieved correctly, but when I set the state with setState(), the state remains "" (empty). What is the problem?

**Comment by Aymkdn** [comment]
Which value do you pass to setValue?

**Comment by smashek** [comment]
@Aymkdn `$tuya->setState(["name" => "deviceName", "value" => "on"])` - but this is working. it is switching it on. but when i wont to check state of deviceName it is still empty (off)

**Comment by Aymkdn** [comment]
And what about the result of `getDevices()`? Because `getState()` uses `getDevices()` and filter it based on the provided name/id.

If the result of `getDevices()` doesn't show the correct state, then I don't know. It's just calling the API and display the result…

**Comment by smashek** [comment]
If i do `$tuya->getDevices()` i am getting devices but state is still empty. If i do `$tuya->setState`, getDevices() inside setState() is empty

**Comment by Aymkdn** [comment]
I'm using the Home Assistant endpoint: https://px1.tuyaeu.com/homeassistant

Try maybe to follow the instructions on https://www.home-assistant.io/integrations/tuya/ and let me know if you see any difference!

**Comment by smashek** [comment]
Ok, ill do that in the evening. Thanks

**Comment by smashek** [comment]
ok, I checked. In [https://www.home-assistant.io/integrations/tuya/](url) everything is ok, i have this problem only in [https://px1.tuyaeu.com/homeassistant](url)

**Comment by Aymkdn** [comment]
So you created an account and followed all the steps in the developer website?

Then I'm sorry, but I don't know what is the issue.

**Comment by smashek** [comment]
Yes, i did. Im sorry too.

**Comment by smashek** [comment]
Hi there. I checked everything one more time in Home Assistance and nothing is good in this api. When i do `{"state": "on"}'` in my switch, state is changing in ON in Home Assistance, but switch doesnt turning on. But if i do it in Home Assistance site [http://192.168.2.104:8123/](url) , everything is going great.

**Comment by Aymkdn** [comment]
Everything is working fine for me for my lights. It's using the home assistant end point, and it's based on another Javascript project.

I don't have a switch so I cannot confirm...

**Comment by Aymkdn** [comment]
This repository is based on https://github.com/unparagoned/cloudtuya that is based on https://github.com/PaulAnnekov/tuyaha, that now indicates the current solution is obsolete. So I guess it works fine with me because I'm using the light only, but maybe for some other devices it won't work.

I'll have to go through the [new Pyton project](https://github.com/tuya/tuya-iot-python-sdk) and translate everything in PHP to update my lib, which could take some weeks of work.

**Comment by Aymkdn** [comment]
Are you sure you region is EU? When you're on iot.tuya.com the region will appear in the URL. For me it's EU, and if I switch to WE then no devices is returned.

I don't know where you're located, but maybe you need to try a different region?

**Comment by smashek** [comment]
Yes, i have eu region set. I will try different later. Thanks for hint

**Comment by smashek** [comment]
Now, couple days later, everything work fine. I don't know how and why. Thanks.

**Comment by Aymkdn** [comment]
Wow… OK… I'm glad it now works :)
