### ISSUE TITLE
set brightness on dimmer

### ISSUE THREAD

**Issue by Aymkdn** [Aymkdn/tuyacloud-php#13]
Hello,
I've a problem to set brigtness on my dimmer. On/Off works fine. But "colorset" doesn't.

`$tuya->setState([
  "name" => "PV Dimmer",
  "command" => "colorSet",
  "value" => [
    "brightness" => 10
  ]
]);`

_Originally posted by @hochland123 in https://github.com/Aymkdn/tuyacloud-php/issues/5#issuecomment-1178654542_

**Comment by Aymkdn** [comment]
Moving your issue to another thread.

Did you try the below:
```php
$tuya->setState([
   "name" => "PV Dimmer",
   "command" => "brightnessSet",
   "value" => 50
]);
```

**Comment by hochland123** [comment]
Hey, it works. Thank you a lot.
