### ISSUE TITLE
Unable to Login.

### ISSUE THREAD

**Issue by shamimbdpro** [Aymkdn/tuyacloud-php#18]
Hi @Aymkdn Can you check why i'm getting this issue. 
![image](https://user-images.githubusercontent.com/39990205/224537804-06c3b94b-0568-4779-a0ae-bf88601b8c2b.png)
I'm trying with Country code 880 for Bangladesh and Region eu

**Comment by Aymkdn** [comment]
The problem is due to your PHP installation. Please, refer to https://www.google.com/search?q=call+to+undefined+function+shm_attach

You need "shm" features within your PHP installation.

**Comment by shamimbdpro** [comment]
@Aymkdn Thanks it work in live server where has installed your recommended extension. Cloud you please let me know how i can get device status? 
i have switch off my bulb in Tuya App but nothing happen in device list object?

**Comment by Aymkdn** [comment]
Tuya prevents to get data too often. So "getDevices" will return a cache data until the delay is reached. The delay may vary and it's auto set based on what the Tuya request returned.

Then you need to wait for a few minutes to get an accurate information.

**Comment by Aymkdn** [comment]
Tuya prevents to get data too often. So "getDevices" will return a cache data until the delay is reached. The delay may vary and it's auto set based on what the Tuya request returned.

Then you need to wait for a few minutes to get an accurate information.

Before it was a one minute delay but they increased it.
