### ISSUE TITLE
Methods with the same name as their class will not be constructors in a future version of PHP; TuyaCloud has a deprecated constructor

### ISSUE THREAD

**Issue by chaaawles** [Aymkdn/tuyacloud-php#2]
Received an error "Methods with the same name as their class will not be constructors in a future version of PHP; TuyaCloud has a deprecated constructor"
![image](https://user-images.githubusercontent.com/52267922/85986242-80264b80-ba1e-11ea-93b4-a6e0d20207eb.png)

**Comment by Aymkdn** [comment]
You can change:
```php
function TuyaCloud($profile) {
```

to
```php
function __construct($profile) {
```
