### ISSUE TITLE
Color Set

### ISSUE THREAD

**Issue by bon-the-one** [Aymkdn/tuyacloud-php#5]
Hi Aymkdn,

Nice code in tuyacloud-php, and can set brightness, power for a bulb. How can I set a color though please? It is not documented?

Thanks,
Bon

**Comment by Aymkdn** [comment]
Check https://github.com/Aymkdn/tuyacloud-php/blob/595c3714abe891ba2ca088e53a2c6c426d354105/TuyaCloud.php#L147

You should be able to use `colorSet`. I don't use it and I'm not at home this weekend. So try to investigate on your side, and let me know. If you don't understand what to do, I'll try to help you on Tuesday.

**Comment by bon-the-one** [comment]
Hi Aymkdn,

Thanks for reply, have a good weekend!

I'm experimenting with HSV values but none change the bulb. I think it's the format I'm sending the request in, but there is no error trapping, so I'm shooting in the dark. Have sent many different format values before bothering you, and am now stuck!

Tuesday is no prob if you have a chance to experiment then,

Thanks,

Bon

**Comment by Aymkdn** [comment]
I don't have a lightbulb, but based on https://github.com/PaulAnnekov/tuyaha/blob/5c47ce40062ab388af994299d6cf63c4add4f899/tuyaha/devices/light.py#L145-L154:
```py
        hsv_color = {
            "hue": color[0] if color[1] != 0 else 0,  # color white
            "saturation": color[1] / 100,
        }
        if len(color) < 3:
            hsv_color["brightness"] = cur_brightness
        else:
            hsv_color["brightness"] = color[2]
        # color white
        white_mode = hsv_color["saturation"] == 0
```

And based on https://github.com/PaulAnnekov/tuyaha/blob/cd9baa85052028fdcf6f1ed222fb6f188016cd06/tuyaha/devices/light.py#L156:
```py
   if self._control_device("colorSet", {"color": hsv_color}):
```

It seems the `hsv_color` format should be a JSON object (see [this issue](https://github.com/PaulAnnekov/tuyaha/issues/17) for some examples):
```json
{
  "color": {
    "hue":40,
    "saturation":255,
    "brightness":255
  }
}
```

Then the command might be:
```php
$tuya->setState([
  "name" => "lightbulb 1",
  "command" => "colorSet",
  "value" => [
    "color" => [
      "hue" => 40,
      "saturation" => 255,
      "brightness" => 255
    ]
  ]
]);
```

But I think it won't work ([based on this example](https://github.com/PaulAnnekov/tuyaha/issues/17#issuecomment-623109330)).

If it doesn't work, then try to replace https://github.com/Aymkdn/tuyacloud-php/blob/595c3714abe891ba2ca088e53a2c6c426d354105/TuyaCloud.php#L184

with:
```php
        "color" => $value
```

And then call it with:
```php
$tuya->setState([
  "name" => "lightbulb 1",
  "command" => "colorSet",
  "value" => [
    "hue" => 40,
    "saturation" => 255,
    "brightness" => 255
  ]
]);
```

Please, let me know the result of your tests and I'll update the file based on your feedback.

**Comment by jonshuttsnap40** [comment]
Just looked at this, but adding `"color" => $options['color']' ` into the tuyacloud.php, then passing in `color` with the 3 values worked. May try and make a PR

**Comment by Aymkdn** [comment]
OK Great! I'll modify my code by the end of the week!

**Comment by Aymkdn** [comment]
I've just published a new version: can you try it, please?

It will check if the command is `colorSet` and in that case it will use `color` instead of `value` in what is sent to the server. Also I've added some additional info [in the "documentation"](https://github.com/Aymkdn/tuyacloud-php/blob/21f01c160f7401c074dbcda017a115759011ecdf/TuyaCloud.php#L147).

So if you try the below with the new version, it should work:
```php
$tuya->setState([
  "name" => "lightbulb 1",
  "command" => "colorSet",
  "value" => [
    "hue" => 40,
    "saturation" => 255,
    "brightness" => 255
  ]
]);
```

As well as:
```php
$tuya->setState([
  "name" => "lightbulb 1",
  "command" => "turnOnOff",
  "value" => 0
]);
```

**Comment by hochland123** [comment]
Hello,
I've a problem to set brigtness on my dimmer. On/Off works fine. But "colorset" doesn't.

`$tuya->setState([
  "name" => "PV Dimmer",
  "command" => "colorSet",
  "value" => [
    "brightness" => 10
  ]
]);`

**Comment by Aymkdn** [comment]
Did you try to define all hue, saturation and brightness?

```php
$tuya->setState([
  "name" => "PV Dimmer",
  "command" => "colorSet",
  "value" => [
    "hue" => 40,
    "saturation" => 255,
    "brightness" => 255
  ]
]);
```

**Comment by hochland123** [comment]
Yes, but also no function. A dimmer has no hue and saturation.

**Comment by Aymkdn** [comment]
I moved your issue to there: https://github.com/Aymkdn/tuyacloud-php/issues/13

**Comment by hochland123** [comment]
What does it mean?
