### ISSUE TITLE
issue with colorSet

### ISSUE THREAD

**Issue by Aymkdn** [Aymkdn/tuyacloud-php#6]
I open the issue here for you @RadioBon:
> tried:
> $tuya->setState([
> "name" => "Kitchen Ceiling",
> "command" => "colorSet",
> "value" => [
> "hue" => 40,
> "saturation" => 255,
> "brightness" => 255
> ]
> ]);
> 
> But still no change... :(
> Any other ideas?

**Comment by Aymkdn** [comment]
Did you try to turn it on/off ? Does it work?
```php
$tuya->setState([
  "name" => "Kitchen Ceiling",
  "value" => "on"
]);
```

**Comment by RadioBon** [comment]
Hey Aymkdn,

Using the following code, all work perfectly (I'm hashing out the bulb id, obviously!)... So the color issue is weird!

// Name: Kitchen Ceiling
$tuya->setState([
  "id" => "7577######",
  "value" => "on"
]);

$tuya->setState([
"id" => "7577######",
"command" => "brightnessSet",
"value" => "254"
]);

$tuya->setState([
  "id" => "7577######",
  "value" => "off"
]);

**Comment by RadioBon** [comment]
The Tuya app changes color perfectly, so I'm not sure why the API won't?

**Comment by Aymkdn** [comment]
OK so at least we know the other commands work.

I'm not sure why it's not working. Based on https://github.com/PaulAnnekov/tuyaha/blob/5c47ce40062ab388af994299d6cf63c4add4f899/tuyaha/devices/light.py#L156 we can see we must replace `value` by `color`, and it's what I did [in the last release](https://github.com/Aymkdn/tuyacloud-php/blob/21f01c160f7401c074dbcda017a115759011ecdf/TuyaCloud.php#L179) (BTW you have the last version of my file??)

Can you add a debug line? To see what is the response from Tuya?
On [line 193](https://github.com/Aymkdn/tuyacloud-php/blob/21f01c160f7401c074dbcda017a115759011ecdf/TuyaCloud.php#L193), you can add:
```php
    $json = $this->post($this->uri.'/skill', [
      "header" => [
        "name" => $options['command'],
        "namespace" => 'control',
        "payloadVersion" => 1
      ],
      "payload" => $payload
    ]);
    echo json_encode($json); // LINE TO ADD
    return $json->header->code === "SUCCESS";
```

This line should show what the server replied.

**Comment by RadioBon** [comment]
Aymkdn,

I'm a fool, I did not realise you had updated the code since the version I was using! Commit 21f01c1 has been downloaded and now it works perfectly.

Thank You for your support and writing this really great utility,

Ian

**Comment by Aymkdn** [comment]
Ahah ! I'm glad it works :)
