### ISSUE TITLE
[tuyacloud] Unable to login

### ISSUE THREAD

**Issue by jaclerigo** [Aymkdn/tuyacloud-php#8]
Hello,

wes trying to use your PHP Library to access to the SmartLife / Tuya objects, but I'm getting this error all the time:

PHP Fatal error:  Uncaught Exception: [tuyacloud] Unable to login: {"responseStatus":"error","errorMsg":"you cannot auth exceed once in 60 seconds"}

Can you help me figuring out what's happening?

Best,
JAC

**Comment by Aymkdn** [comment]
You must not call `new TuyaCloud` more than once every minute.

**Comment by jaclerigo** [comment]
I've thought that could be the problem, but I've tried with spacing the request by five minutes, and even hours, and the error was every time the same.

Reviewing my code, there was a missing letter in my login email, and the error mislead me. That was it and now is working fine. Thank you.
