### ISSUE TITLE
accessToken

### ISSUE THREAD

**Issue by AndreXori** [Aymkdn/tuyacloud-php#9]
Hey mate! Congrats for the code!

How/where do I get the **accessToken**? Didn't get that. In tuya's cloud I just have access ID and access Secret. Tried to use both with no luck.

Thanks

**Comment by Aymkdn** [comment]
No need for the access token. You need to provide your username and password:
```php
$tuya = new TuyaCloud([
  "userName" => "email@domain.com", // username/email to access to SmartLife/Tuya app
  "password" => "MyPassword", // password to access to SmartLife/Tuya app
  "bizType" => "smart_life", // type ('tuya' or 'smart_life')
  "countryCode" => "33", // Country code (International dialing number), e.g. "33" for France or "1" for USA
  "region" => "eu" // region (az=Americas, ay=Asia, eu=Europe)
]);
```

**Comment by AndreXori** [comment]
Using just these information I got this error:

> PHP Fatal error:  Uncaught exception 'Exception' with message '[tuyacloud] Unable to login: ' in /home/bkdsdd9p/public_html/tuya/TuyaCloud.php:79
> Stack trace:
> #0 /home/bkdsdd9p/public_html/tuya/TuyaCloud.php(82): TuyaCloud->login(5)
> #1 /home/bkdsdd9p/public_html/tuya/TuyaCloud.php(82): TuyaCloud->login(4)
> #2 /home/bkdsdd9p/public_html/tuya/TuyaCloud.php(82): TuyaCloud->login(3)
> #3 /home/bkdsdd9p/public_html/tuya/TuyaCloud.php(82): TuyaCloud->login(2)
> #4 /home/bkdsdd9p/public_html/tuya/TuyaCloud.php(82): TuyaCloud->login(1)
> #5 /home/bkdsdd9p/public_html/tuya/TuyaCloud.php(25): TuyaCloud->login()
> #6 /home/bkdsdd9p/public_html/tuya/index.php(10): TuyaCloud->__construct(Array)
> #7 {main}
>   thrown in /home/bkdsdd9p/public_html/tuya/TuyaCloud.php on line 79

**Comment by Aymkdn** [comment]
Your problem is probably different. Make sure you use the correct login information.

**Comment by cocobln** [comment]
Are there any news on that topic? I have the same issues and i can make sure the login data is correct.

I red Tuya changed the verification method. Maybe thats the reason.

**Comment by Aymkdn** [comment]
It works for me... So it might not be that.

**Comment by Thunderscreech** [comment]
For anyone drifting in here from Google, here was my finding.  I had changed the countryCode and region to 1/az (for USA/Americas) as the comments in the code suggested and I got the same error as above.

I changed it back to 33/eu (France/EU) and... it worked.  The comment about region/country in the code was the culprit.

**Comment by Aymkdn** [comment]
Good to know! Thanks for sharing!

**Comment by shamimbdpro** [comment]
Hi @Aymkdn i see this issue with country code 880 for Bangladesh and Region bd for Bangladesh.  
![image](https://user-images.githubusercontent.com/39990205/224537672-bf425328-f856-4882-864a-b7f170ec8d8c.png)
